#Insert into Gives table#
INSERT INTO gives VALUES (1,2016,'College choice', 'Harvard University', 'MBA', 1, 98)
INSERT INTO gives VALUES (2,2016,'College Choice', 'University of California Berkeley', 'MBA', 2, 98)
INSERT INTO gives VALUES (3,2016,'USNews', 'Harvard University', 'MBA', 1, 98)
INSERT INTO gives VALUES (4,2016,'USNews', 'Stanford University', 'MBA', 2, 98.3)
INSERT INTO gives VALUES (5,2015,'USNews', 'Stanford University', 'MBA', 1, 99)
INSERT INTO gives VALUES (6,2015,'USNews', 'Harvard University', 'MBA', 2, 98.8)
INSERT INTO gives VALUES (7,2015,'TFE Times', 'New York University', 'MSBA', 1, 99)
INSERT INTO gives VALUES (8,2015,'TFE Times', 'University of Southern California', 'MSBA', 2, 98)
INSERT INTO gives VALUES (10,2016,'Masters in Data Science', 'MIT', 'MSBA', 1, 98.75)
INSERT INTO gives VALUES (11,2016,'Masters in Data Science', 'Carnegie Mellon University', 'MSBA', 2, 97.25)
INSERT INTO gives VALUES (12,2016,'Masters in Data Science', 'University of Texas Austin', 'MSBA', 3, 97.7)
INSERT INTO gives VALUES (13,2016,'College Choice', 'University of Texas Austin', 'MIS', 1, 98.3)
INSERT INTO gives VALUES (14,2016,'College Choice', 'MIT', 'MIS', 2, 98.6)
INSERT INTO gives VALUES (15,2016,'College Choice', 'University of Minnesota', 'MIS', 3, 97)
INSERT INTO gives VALUES (16,2016,'College Choice', 'University of Arizona', 'MIS', 4, 95.5)
INSERT INTO gives VALUES (17,2016,'College Choice', 'Carnegie Mellon University', 'MIS', 5, 96.8)
INSERT INTO gives VALUES (18,2016,'College Choice', 'University of Maryland', 'MIS', 6, 94)
INSERT INTO gives VALUES (19,2016,'US News', 'MIT', 'MIS', 1, 99)
INSERT INTO gives VALUES (20,2016,'US News', 'Carnegie Mellon University', 'MIS', 2, 96.8)
INSERT INTO gives VALUES (21,2016,'US News', 'University of Arizona', 'MIS', 5, 95.5)
INSERT INTO gives VALUES (22,2016,'US News', 'New York University', 'MIS', 6, 95.66)
INSERT INTO gives VALUES (23,2017,'US News', 'University of Chicago', 'MBA', 2, )
INSERT INTO gives VALUES (24,2017,'US News', 'University of Pennsylvania', 'MBA', 3, )
INSERT INTO gives VALUES (25,2017,'US News', 'MIT', 'MBA', 5, )
INSERT INTO gives VALUES (26,2017,'US News', 'Northwestern University', 'MBA', 5, )
INSERT INTO gives VALUES (27,2017,'US News', 'University of California Berkeley', 'MBA', 7, )
INSERT INTO gives VALUES (28,2017,'US News', 'Dartmouth College', 'MBA', 8, )
INSERT INTO gives VALUES (39,2015,'US News', 'University of Pennsylvania', 'MBA', 3, )
INSERT INTO gives VALUES (40,2015,'US News', 'University of Chicago', 'MBA', 4, )
INSERT INTO gives VALUES (41,2015,'US News', 'MIT', 'MBA', 5, )
INSERT INTO gives VALUES (42,2015,'US News', 'Northwestern University', 'MBA', 6, )
INSERT INTO gives VALUES (43,2015,'US News', 'University of California Berkeley', 'MBA', 7, )
INSERT INTO gives VALUES (44,2015,'US News', 'Columbia University', 'MBA', 8, )
INSERT INTO gives VALUES (45,2015,'US News', 'Dartmouth College', 'MBA', 9, )
INSERT INTO gives VALUES (46,2015,'US News', 'University of Virginia', 'MBA', 10, )
INSERT INTO gives VALUES (47,2016,'Economist', 'University of Chicago', 'MBA', 1, )
INSERT INTO gives VALUES (48,2016,'Economist', 'Northwestern University', 'MBA', 2, )
INSERT INTO gives VALUES (49,2016,'Economist', 'University of Virginia', 'MBA', 3, )
INSERT INTO gives VALUES (50,2016,'Economist', 'Harvard University', 'MBA', 4, 98)
INSERT INTO gives VALUES (51,2016,'Economist', 'Stanford University', 'MBA', 5, 99)
INSERT INTO gives VALUES (52,2016,'Economist', 'Dartmouth College', 'MBA', 6, )
INSERT INTO gives VALUES (53,2016,'Economist', 'University of California Berkeley', 'MBA', 7, )
INSERT INTO gives VALUES (54,2016,'Economist', 'Columbia University', 'MBA', 8, )
INSERT INTO gives VALUES (55,2016,'Economist', 'University of Pennsylvania', 'MBA', 9, )
INSERT INTO gives VALUES (56,2016,'Economist', 'University of California Los Angeles', 'MBA', 10, )
INSERT INTO gives VALUES (31,2017,'US News', 'Yale University', 'MBA', 8, )
INSERT INTO gives VALUES (32,2017,'US News', 'Columbia University', 'MBA', 10, )
INSERT INTO gives VALUES (33,2017,'US News', 'University of Virginia', 'MBA', 11, )
INSERT INTO gives VALUES (34,2017,'US News', 'Duke University', 'MBA', 12, )
INSERT INTO gives VALUES (35,2017,'US News', 'University of Michigan Ann Arbor', 'MBA', 12, )
INSERT INTO gives VALUES (36,2017,'US News', 'Cornell University', 'MBA', 14, )
INSERT INTO gives VALUES (37,2017,'US News', 'University of California Los Angeles', 'MBA', 15, )
INSERT INTO gives VALUES (57,2016,'College choice', 'Georgia Intitute of Technology', 'MIS', 7, )
INSERT INTO gives VALUES (58,2016,'College choice', 'Arizona State University', 'MIS', 8, )
INSERT INTO gives VALUES (59,2016,'College choice', 'Stanford University', 'MIS', 9, )
INSERT INTO gives VALUES (60,2016,'College choice', 'University of Texas Dallas', 'MIS', 10, )
INSERT INTO gives VALUES (61,2016,'College choice', 'University of Pennsylvania', 'MIS', 11, )
INSERT INTO gives VALUES (62,2016,'College choice', 'Georgia State University', 'MIS', 12, )
INSERT INTO gives VALUES (63,2016,'College choice', 'New York University', 'MIS', 14, )
INSERT INTO gives VALUES (64,2016,'College choice', 'University of California Berkeley', 'MIS', 15, )
INSERT INTO gives VALUES (65,2016,'Masters in Data Science', 'University of Chicago', 'MSBA', 4, 98.75)
INSERT INTO gives VALUES (66,2016,'Masters in Data Science', 'Columbia University', 'MSBA', 5, 98.75)
INSERT INTO gives VALUES (67,2016,'Masters in Data Science', 'Duke University', 'MSBA', 6, 98.75)
INSERT INTO gives VALUES (68,2016,'Masters in Data Science', 'Georgia Intitute of Technology', 'MSBA', 7, 98.75)
INSERT INTO gives VALUES (69,2016,'Masters in Data Science', 'Purdue University', 'MSBA', 8, 98.75)
INSERT INTO gives VALUES (70,2016,'Masters in Data Science', 'University of Minnesota', 'MSBA', 9, 98.75)
INSERT INTO gives VALUES (71,2016,'Masters in Data Science', 'New York University', 'MSBA', 10, 98.75)
INSERT INTO gives VALUES (72,2015,'TFE Times', 'University of Rochester', 'MSBA', 3, )
INSERT INTO gives VALUES (73,2015,'TFE Times', 'Rensselaer Polytechnic Institute', 'MSBA', 4, )
INSERT INTO gives VALUES (74,2015,'TFE Times', 'University of Texas Austin', 'MSBA', 5, )
INSERT INTO gives VALUES (75,2015,'TFE Times', 'Fordham University', 'MSBA', 6, )
INSERT INTO gives VALUES (76,2015,'TFE Times', 'Southern Methodist University', 'MSBA', 7, )
INSERT INTO gives VALUES (77,2015,'TFE Times', 'Villanova University', 'MSBA', 8, )
INSERT INTO gives VALUES (78,2015,'TFE Times', 'Arizona State University', 'MSBA', 9, )
INSERT INTO gives VALUES (79,2015,'TFE Times', 'Stevens Institute of Technology', 'MSBA', 10, )
INSERT INTO gives VALUES (80,2017,'TFE Times', 'University of Southern California', 'MSBA', 1, 98)
INSERT INTO gives VALUES (81,2017,'TFE Times', 'New York University', 'MSBA', 2, )
INSERT INTO gives VALUES (82,2017,'TFE Times', 'Rensselaer Polytechnic Institute', 'MSBA', 3, )
INSERT INTO gives VALUES (83,2017,'TFE Times', 'University of Rochester', 'MSBA', 4, )
INSERT INTO gives VALUES (84,2017,'TFE Times', 'Villanova University', 'MSBA', 5, )
INSERT INTO gives VALUES (85,2017,'TFE Times', 'Arizona State University', 'MSBA', 6, )
INSERT INTO gives VALUES (86,2017,'TFE Times', 'Stevens Institute of Technology', 'MSBA', 7, )
INSERT INTO gives VALUES (87,2017,'TFE Times', 'University of Texas Austin', 'MSBA', 8, )
INSERT INTO gives VALUES (88,2017,'TFE Times', 'University of Texas Dallas', 'MSBA', 9, )
INSERT INTO gives VALUES (89,2017,'TFE Times', 'Michigan State University', 'MSBA', 10, )



#Insert into Offers table#
INSERT INTO offers VALUES ('Arizona State University', 'MIS', 42086, 12, 'W.P.Carey School of Business')
INSERT INTO offers VALUES ('Arizona State University', 'MSBA', 51700, 9, 'W.P.Carey School of Business')
INSERT INTO offers VALUES ('Carnegie Mellon University', 'MIS', 60000, 16, 'Heinz College')
INSERT INTO offers VALUES ('Carnegie Mellon University', 'MIS', 97119, 16, 'Heinz College')
INSERT INTO offers VALUES ('Carnegie Mellon University', 'MSBA', 68250, 16, 'Heinz College')
INSERT INTO offers VALUES ('Columbia University', 'MBA', 65998, 24, 'Columbia Business School')
INSERT INTO offers VALUES ('Columbia University', 'MSBA', 69192, 16, 'School of Professional Studies')
INSERT INTO offers VALUES ('Cornell University', 'MBA', 59500, 21, 'Johnson School Of Business')
INSERT INTO offers VALUES ('Dartmouth College', 'MBA', 64200, 24, 'Tuck School of Business')
INSERT INTO offers VALUES ('Duke University', 'MBA', 60600, 24, 'Fuqua School Of Business')
INSERT INTO offers VALUES ('Duke University', 'MSBA', 65000, 10, 'Fuqua School Of Business')
INSERT INTO offers VALUES ('Fordham University', 'MSBA', , 12, 'Gabelli School of Business')
INSERT INTO offers VALUES ('Georgia Intitute of Technology', 'MIS', 39484, 22, 'Scheller College of Business')
INSERT INTO offers VALUES ('Georgia Intitute of Technology', 'MSBA', , 12, 'Scheller College of Business')
INSERT INTO offers VALUES ('Georgia State University', 'MIS', 40226, 12, 'Robinson College of Business')
INSERT INTO offers VALUES ('Harvard University', 'MBA', 58875, 24, 'Harvard Business School')
INSERT INTO offers VALUES ('MIT', 'MBA', 65446, 24, 'Sloan School of Management')
INSERT INTO offers VALUES ('MIT', 'MIS', 65750, , 'Sloan School of Management')
INSERT INTO offers VALUES ('MIT', 'MIS', 65750, 9, 'Sloan School of Management')
INSERT INTO offers VALUES ('MIT', 'MSBA', 75000, 12, 'Sloan School of Management')
INSERT INTO offers VALUES ('Michigan State University', 'MSBA', 39000, 12, 'Eli Broad College of Business')
INSERT INTO offers VALUES ('New York University', 'MIS', 63720, , 'Stern School of Business')
INSERT INTO offers VALUES ('New York University', 'MIS', 63720, 24, 'Courant school of technology and Stern School of Business')
INSERT INTO offers VALUES ('New York University', 'MSBA', 70800, 12, 'Stern Business School')
INSERT INTO offers VALUES ('New York University', 'MSBA', 70800, 12, 'Stern School of Business')
INSERT INTO offers VALUES ('Northwestern University', 'MBA', 64,059 , 24, 'Kellog School of Management')
INSERT INTO offers VALUES ('Purdue University', 'MSBA', 46000, 11, 'Krannert School of Management')
INSERT INTO offers VALUES ('Rensselaer Polytechnic Institute', 'MSBA', 49520, 9, 'Lally School of Management')
INSERT INTO offers VALUES ('Southern Methodist University', 'MSBA', 41850, 9, 'Cox School of Business')
INSERT INTO offers VALUES ('Stanford University', 'MBA', 47940, 24, 'Graduate School of Business')
INSERT INTO offers VALUES ('Stanford University', 'MIS', 64050, 24, 'Graduate School of Business')
INSERT INTO offers VALUES ('Stevens Institute of Technology', 'MSBA', , , 'School of Business')
INSERT INTO offers VALUES ('University of Arizona', 'MIS', 41884, 16, 'Eller school of Management')
INSERT INTO offers VALUES ('University of Arizona', 'MIS', 65702, 16, 'Eller school of Management')
INSERT INTO offers VALUES ('University of California Berkeley', 'MBA', 53907, 24, 'Haas Business School')
INSERT INTO offers VALUES ('University of California Berkeley', 'MBA', 55968, 24, 'Haas Business School')
INSERT INTO offers VALUES ('University of California Berkeley', 'MIS', 55968, 24, 'School of Information')
INSERT INTO offers VALUES ('University of California Los Angeles', 'MBA', 50517, 24, 'Anderson School Of Business')
INSERT INTO offers VALUES ('University of Chicago', 'MBA', 63890, 24, 'Booth School of Business')
INSERT INTO offers VALUES ('University of Chicago', 'MSBA', 4385, 12, 'Graham School')
INSERT INTO offers VALUES ('University of Maryland', 'MIS', 60000, 16, 'Robert H Smith')
INSERT INTO offers VALUES ('University of Michigan Ann Arbor', 'MBA', 61590, 24, 'Ross School Of Business')
INSERT INTO offers VALUES ('University of Minnesota', 'MIS', 46500, 24, ' Carlson School of Management')
INSERT INTO offers VALUES ('University of Minnesota', 'MSBA', 58500, 12, ' Carlson School of Management')
INSERT INTO offers VALUES ('University of Pennsylvania', 'MBA', 64920, 24, 'Wharton School')
INSERT INTO offers VALUES ('University of Pennsylvania', 'MIS', 64920, 24, 'Wharton School')
INSERT INTO offers VALUES ('University of Rochester', 'MSBA', 63000, 12, 'Simon Business Schol')
INSERT INTO offers VALUES ('University of Southern California', 'MSBA', 58674, 18, 'Marshall Business School')
INSERT INTO offers VALUES ('University of Texas Austin', 'MIS', 48832, 18, 'McCombs School of Business')
INSERT INTO offers VALUES ('University of Texas Austin', 'MSBA', 44000, 10, 'McCombs School of Business')
INSERT INTO offers VALUES ('University of Texas Dallas', 'MIS', 30855, 24, 'Naveen Jindal school of Management')
INSERT INTO offers VALUES ('University of Texas Dallas', 'MSBA', 30855, 24, 'Naveen Jindal school of Management')
INSERT INTO offers VALUES ('University of Virginia', 'MBA', 55518, 24, 'Darden School of Business')
INSERT INTO offers VALUES ('Villanova University', 'MSBA', 39265, 20, 'School of Business')
INSERT INTO offers VALUES ('Yale University', 'MBA', 61500, 24, 'Yale School Of Management')